import Foundation

// MARK: - 액션 메타데이터 테이블 (R-09 + i18n)

/// displayName/systemImage/category 3스위치의 단일 출처.
/// 추가 시 여기 1곳만 갱신하면 된다. 누락은 ApexKeyMetadataTests가 잡는다.
struct ActionMetadata {
    let displayNameKey: String
    let systemImage: String
    let category: ActionCategory
    
    var displayName: String {
        displayNameKey.localized
    }
}

extension ActionType {
    static let metadata: [ActionType: ActionMetadata] = [
        .launchApp: ActionMetadata(displayNameKey: "action.launchApp", systemImage: "square.and.arrow.up", category: .essential),
        .menuCommand: ActionMetadata(displayNameKey: "action.menuCommand", systemImage: "menubar", category: .essential),
        .file: ActionMetadata(displayNameKey: "action.file", systemImage: "folder", category: .essential),
        .url: ActionMetadata(displayNameKey: "action.url", systemImage: "link", category: .essential),
        .script: ActionMetadata(displayNameKey: "action.script", systemImage: "terminal", category: .essential),
        .system: ActionMetadata(displayNameKey: "action.system", systemImage: "gearshape", category: .essential),
        .paste: ActionMetadata(displayNameKey: "action.paste", systemImage: "clipboard", category: .essential),
        .wait: ActionMetadata(displayNameKey: "action.wait", systemImage: "clock", category: .essential),
        .coordinateClick: ActionMetadata(displayNameKey: "action.coordinateClick", systemImage: "mousepointer", category: .essential),
        .pauseUntilInput: ActionMetadata(displayNameKey: "action.pauseUntilInput", systemImage: "pause.circle", category: .essential),
        .macro: ActionMetadata(displayNameKey: "action.macro", systemImage: "record", category: .essential),
        .dialog: ActionMetadata(displayNameKey: "action.dialog", systemImage: "text.bubble", category: .essential),
        .text: ActionMetadata(displayNameKey: "action.text", systemImage: "text.alignleft", category: .essential),
        .clipText: ActionMetadata(displayNameKey: "action.clipText", systemImage: "doc.on.clipboard", category: .essential),
        .moveToFront: ActionMetadata(displayNameKey: "action.moveToFront", systemImage: "arrow.up.forward.app", category: .essential),
        .wakeDisplay: ActionMetadata(displayNameKey: "action.wakeDisplay", systemImage: "display", category: .essential),
        .clearRecents: ActionMetadata(displayNameKey: "action.clearRecents", systemImage: "clock.arrow.circlepath", category: .essential),
        .preventSleep: ActionMetadata(displayNameKey: "action.preventSleep", systemImage: "moon.zzz", category: .essential),
        .wallpaper: ActionMetadata(displayNameKey: "action.wallpaper", systemImage: "photo", category: .essential),
        .darkMode: ActionMetadata(displayNameKey: "action.darkMode", systemImage: "moon.fill", category: .essential),
        .focusMode: ActionMetadata(displayNameKey: "action.focusMode", systemImage: "moon.circle", category: .essential),
        .screenshot: ActionMetadata(displayNameKey: "action.screenshot", systemImage: "camera.viewfinder", category: .essential),
        .pdf: ActionMetadata(displayNameKey: "action.pdf", systemImage: "doc.richtext", category: .essential),
        .network: ActionMetadata(displayNameKey: "action.network", systemImage: "wifi", category: .essential),
        .bluetooth: ActionMetadata(displayNameKey: "action.bluetooth", systemImage: "antenna.radiowaves.left.and.right", category: .essential),
        .timer: ActionMetadata(displayNameKey: "action.timer", systemImage: "timer", category: .essential),
        .stopwatch: ActionMetadata(displayNameKey: "action.stopwatch", systemImage: "stopwatch", category: .essential),
        .location: ActionMetadata(displayNameKey: "action.location", systemImage: "mappin.circle", category: .essential),
        .airDrop: ActionMetadata(displayNameKey: "action.airDrop", systemImage: "airplayaudio", category: .essential),
        .newQuickNote: ActionMetadata(displayNameKey: "action.newQuickNote", systemImage: "rectangle.dashed.badge.record", category: .essential),
        .newNote: ActionMetadata(displayNameKey: "action.newNote", systemImage: "doc.plaintext", category: .essential),
        .readTable: ActionMetadata(displayNameKey: "action.readTable", systemImage: "tablecells", category: .essential),
        .emailData: ActionMetadata(displayNameKey: "action.emailData", systemImage: "envelope", category: .essential),
        .date: ActionMetadata(displayNameKey: "action.date", systemImage: "calendar", category: .essential),
        .appleScript: ActionMetadata(displayNameKey: "action.appleScript", systemImage: "applelogo", category: .scripting),
        .javaScriptForAutomation: ActionMetadata(displayNameKey: "action.javaScriptForAutomation", systemImage: "chevron.left.forwardslash.chevron.right", category: .scripting),
        .quickLook: ActionMetadata(displayNameKey: "action.quickLook", systemImage: "eye", category: .media),
        .photos: ActionMetadata(displayNameKey: "action.photos", systemImage: "photo.stack", category: .media),
        .musicAndVideo: ActionMetadata(displayNameKey: "action.musicAndVideo", systemImage: "play.circle", category: .media),
        .playMusic: ActionMetadata(displayNameKey: "action.playMusic", systemImage: "music.note", category: .media),
        .playPodcast: ActionMetadata(displayNameKey: "action.playPodcast", systemImage: "mic.circle", category: .media),
        .tuneStation: ActionMetadata(displayNameKey: "action.tuneStation", systemImage: "radio", category: .media),
        .radio: ActionMetadata(displayNameKey: "action.radio", systemImage: "antenna.radiowaves.left.and.right", category: .media),
        .viewPhotos: ActionMetadata(displayNameKey: "action.viewPhotos", systemImage: "photo.on.rectangle", category: .media),
        .album: ActionMetadata(displayNameKey: "action.album", systemImage: "rectangle.stack", category: .media),
        .randomPhoto: ActionMetadata(displayNameKey: "action.randomPhoto", systemImage: "shuffle", category: .media),
        .slideshow: ActionMetadata(displayNameKey: "action.slideshow", systemImage: "rectangle.stack.badge.play", category: .media),
        .getLastPhoto: ActionMetadata(displayNameKey: "action.getLastPhoto", systemImage: "photo.stack", category: .media),
        .camera: ActionMetadata(displayNameKey: "action.camera", systemImage: "camera", category: .media),
        .rotateImage: ActionMetadata(displayNameKey: "action.rotateImage", systemImage: "arrow.triangle.2.circlepath", category: .media),
        .cropImage: ActionMetadata(displayNameKey: "action.cropImage", systemImage: "crop", category: .media),
        .trimVideo: ActionMetadata(displayNameKey: "action.trimVideo", systemImage: "scissors", category: .media),
        .takeScreenshot: ActionMetadata(displayNameKey: "action.takeScreenshot", systemImage: "camera.viewfinder", category: .media),
        .saveOutput: ActionMetadata(displayNameKey: "action.saveOutput", systemImage: "square.and.arrow.down", category: .media),
        .setVolumeMedia: ActionMetadata(displayNameKey: "action.setVolumeMedia", systemImage: "speaker.wave.2", category: .media),
        .moveMedia: ActionMetadata(displayNameKey: "action.moveMedia", systemImage: "folder.move", category: .media),
        .bookmark: ActionMetadata(displayNameKey: "action.bookmark", systemImage: "bookmark", category: .media),
        .podcasts: ActionMetadata(displayNameKey: "action.podcasts", systemImage: "mic.fill", category: .media),
        .news: ActionMetadata(displayNameKey: "action.news", systemImage: "newspaper", category: .media),
        .stocks: ActionMetadata(displayNameKey: "action.stocks", systemImage: "chart.line.uptrend.xyaxis", category: .media),
        .videoDownloader: ActionMetadata(displayNameKey: "action.videoDownloader", systemImage: "arrow.down.circle", category: .media),
        .editDocument: ActionMetadata(displayNameKey: "action.editDocument", systemImage: "doc.text", category: .documents),
        .translate: ActionMetadata(displayNameKey: "action.translate", systemImage: "character.bubble", category: .documents),
        .textEditShortcut: ActionMetadata(displayNameKey: "action.textEditShortcut", systemImage: "textformat", category: .documents),
        .noteActions: ActionMetadata(displayNameKey: "action.noteActions", systemImage: "note.text", category: .documents),
        .createNote: ActionMetadata(displayNameKey: "action.createNote", systemImage: "plus.square.on.square", category: .documents),
        .setParagraphStyle: ActionMetadata(displayNameKey: "action.setParagraphStyle", systemImage: "paragraphsign", category: .documents),
        .newDocument: ActionMetadata(displayNameKey: "action.newDocument", systemImage: "doc.badge.plus", category: .documents),
        .viewDocument: ActionMetadata(displayNameKey: "action.viewDocument", systemImage: "doc.text.magnifyingglass", category: .documents),
        .mail: ActionMetadata(displayNameKey: "action.mail", systemImage: "envelope", category: .documents),
        .setMailBody: ActionMetadata(displayNameKey: "action.setMailBody", systemImage: "text.alignleft", category: .documents),
        .setMailRecipients: ActionMetadata(displayNameKey: "action.setMailRecipients", systemImage: "person.circle", category: .documents),
        .drive: ActionMetadata(displayNameKey: "action.drive", systemImage: "cloud", category: .documents),
        .oneDrive: ActionMetadata(displayNameKey: "action.drive", systemImage: "cloud.fill", category: .documents),
        .box: ActionMetadata(displayNameKey: "action.box", systemImage: "archivebox", category: .documents),
        .getFiles: ActionMetadata(displayNameKey: "action.getFiles", systemImage: "folder.badge.questionmark", category: .documents),
        .moveFiles: ActionMetadata(displayNameKey: "action.moveFiles", systemImage: "folder.move", category: .documents),
        .renameFiles: ActionMetadata(displayNameKey: "action.renameFiles", systemImage: "pencil.circle", category: .documents),
        .extractArchive: ActionMetadata(displayNameKey: "action.extractArchive", systemImage: "archivebox", category: .documents),
        .externalStorage: ActionMetadata(displayNameKey: "action.externalStorage", systemImage: "externaldrive", category: .documents),
        .fileActions: ActionMetadata(displayNameKey: "action.fileActions", systemImage: "doc.text.badge.gearshape", category: .documents),
        .getConfirmation: ActionMetadata(displayNameKey: "action.getConfirmation", systemImage: "questionmark.circle", category: .documents),
        .getAttachment: ActionMetadata(displayNameKey: "action.getAttachment", systemImage: "paperclip", category: .documents),
        .getDictionary: ActionMetadata(displayNameKey: "action.getDictionary", systemImage: "list.bullet.rectangle", category: .documents),
        .dateFormatter: ActionMetadata(displayNameKey: "action.dateFormatter", systemImage: "calendar.badge.clock", category: .documents),
        .listActions: ActionMetadata(displayNameKey: "action.listActions", systemImage: "list.bullet", category: .documents),
        .adjustDate: ActionMetadata(displayNameKey: "action.adjustDate", systemImage: "calendar.badge.minus", category: .documents),
        .formatNumber: ActionMetadata(displayNameKey: "action.formatNumber", systemImage: "number", category: .documents),
        .math: ActionMetadata(displayNameKey: "action.math", systemImage: "function", category: .documents),
        .hash: ActionMetadata(displayNameKey: "action.hash", systemImage: "number.square", category: .documents),
        .uuid: ActionMetadata(displayNameKey: "action.uuid", systemImage: "fingerprint", category: .documents),
        .outputDifference: ActionMetadata(displayNameKey: "action.outputDifference", systemImage: "minus.plus.circle", category: .documents),
        .typeNumber: ActionMetadata(displayNameKey: "action.typeNumber", systemImage: "textformat.123", category: .documents),
        .typeText: ActionMetadata(displayNameKey: "action.typeText", systemImage: "textformat", category: .documents),
        .getClipboard: ActionMetadata(displayNameKey: "action.getClipboard", systemImage: "doc.on.clipboard", category: .documents),
        .setClipboard: ActionMetadata(displayNameKey: "action.setClipboard", systemImage: "doc.on.clipboard.fill", category: .documents),
        .regex: ActionMetadata(displayNameKey: "action.regex", systemImage: "text.magnifyingglass", category: .documents),
        .typeDateTime: ActionMetadata(displayNameKey: "action.typeDateTime", systemImage: "calendar.badge.clock", category: .documents),
        .sort: ActionMetadata(displayNameKey: "action.sort", systemImage: "arrow.up.arrow.down", category: .documents),
        .changeCase: ActionMetadata(displayNameKey: "action.changeCase", systemImage: "textformat.abc", category: .documents),
        .replaceText: ActionMetadata(displayNameKey: "action.replaceText", systemImage: "arrow.triangle.swap", category: .documents),
        .combineText: ActionMetadata(displayNameKey: "action.combineText", systemImage: "rectangle.rightthird.inward", category: .documents),
        .matchText: ActionMetadata(displayNameKey: "action.matchText", systemImage: "checkmark.circle", category: .documents),
        .splitText: ActionMetadata(displayNameKey: "action.splitText", systemImage: "rectangle.split.3x1", category: .documents),
        .trimWhitespace: ActionMetadata(displayNameKey: "action.trimWhitespace", systemImage: "scissors", category: .documents),
        .surroundText: ActionMetadata(displayNameKey: "action.surroundText", systemImage: "text.badge.plus", category: .documents),
        .count: ActionMetadata(displayNameKey: "action.count", systemImage: "number.circle", category: .documents),
        .wordCount: ActionMetadata(displayNameKey: "action.wordCount", systemImage: "text.word.spacing", category: .documents),
        .calculate: ActionMetadata(displayNameKey: "action.calculate", systemImage: "function.math", category: .documents),
        .base64Encode: ActionMetadata(displayNameKey: "action.base64Encode", systemImage: "lock.rotation", category: .documents),
        .htmlToMarkdown: ActionMetadata(displayNameKey: "action.htmlToMarkdown", systemImage: "doc.richtext", category: .documents),
        .measurement: ActionMetadata(displayNameKey: "action.measurement", systemImage: "ruler", category: .documents),
        .scanQRCode: ActionMetadata(displayNameKey: "action.scanQRCode", systemImage: "qrcode.viewfinder", category: .documents),
        .recognizeText: ActionMetadata(displayNameKey: "action.recognizeText", systemImage: "text.viewfinder", category: .documents),
        .recognizeAnimal: ActionMetadata(displayNameKey: "action.recognizeAnimal", systemImage: "pawprint", category: .documents),
        .detectLanguage: ActionMetadata(displayNameKey: "action.detectLanguage", systemImage: "globe", category: .documents),
        .map: ActionMetadata(displayNameKey: "action.map", systemImage: "map", category: .location),
        .transportation: ActionMetadata(displayNameKey: "action.transportation", systemImage: "tram.fill", category: .location),
        .message: ActionMetadata(displayNameKey: "action.message", systemImage: "message", category: .content),
        .email: ActionMetadata(displayNameKey: "action.email", systemImage: "envelope", category: .content),
        .calendar: ActionMetadata(displayNameKey: "action.calendar", systemImage: "calendar", category: .content),
        .reminders: ActionMetadata(displayNameKey: "action.reminders", systemImage: "checkmark.circle", category: .content),
        .webContent: ActionMetadata(displayNameKey: "action.webContent", systemImage: "globe", category: .content),
        .presentation: ActionMetadata(displayNameKey: "action.presentation", systemImage: "rectangle.on.rectangle", category: .content),
        .webIntegration: ActionMetadata(displayNameKey: "action.webIntegration", systemImage: "network", category: .accessories),
        .documentsAndFiles: ActionMetadata(displayNameKey: "action.documentsAndFiles", systemImage: "doc.on.doc", category: .accessories),
        .devicesAndSheet: ActionMetadata(displayNameKey: "action.devicesAndSheet", systemImage: "desktopcomputer", category: .accessories),
        .createShortcutIcon: ActionMetadata(displayNameKey: "action.createShortcutIcon", systemImage: "app.badge", category: .accessories),
        .runShortcut: ActionMetadata(displayNameKey: "action.runShortcut", systemImage: "play.circle", category: .flowControl),
        .repeatLoop: ActionMetadata(displayNameKey: "action.repeatLoop", systemImage: "repeat", category: .flowControl),
        .repeatEach: ActionMetadata(displayNameKey: "action.repeatEach", systemImage: "list.number", category: .flowControl),
        .ifElse: ActionMetadata(displayNameKey: "action.ifElse", systemImage: "arrow.triangle.branch", category: .flowControl),
        .endRepeat: ActionMetadata(displayNameKey: "action.endRepeat", systemImage: "stop.circle", category: .flowControl),
        .stopShortcut: ActionMetadata(displayNameKey: "action.stopShortcut", systemImage: "xmark.circle", category: .flowControl),
        .chooseFromMenu: ActionMetadata(displayNameKey: "action.chooseFromMenu", systemImage: "list.bullet.rectangle", category: .flowControl),
        .comment: ActionMetadata(displayNameKey: "action.comment", systemImage: "bubble.left", category: .flowControl),
        .setVariable: ActionMetadata(displayNameKey: "action.setVariable", systemImage: "text.badge.plus", category: .variables),
        .variableDetail: ActionMetadata(displayNameKey: "action.variableDetail", systemImage: "info.circle", category: .variables),
        .clipboardAction: ActionMetadata(displayNameKey: "action.clipboardAction", systemImage: "doc.on.clipboard", category: .variables),
        .runScriptInShell: ActionMetadata(displayNameKey: "action.runScriptInShell", systemImage: "terminal", category: .flowControl),
        .number: ActionMetadata(displayNameKey: "action.number", systemImage: "number", category: .variables),
        .outputToVariable: ActionMetadata(displayNameKey: "action.outputToVariable", systemImage: "arrow.right.circle", category: .variables),
        .useModel: ActionMetadata(displayNameKey: "action.useModel", systemImage: "sparkles", category: .ai),
        .writingTool: ActionMetadata(displayNameKey: "action.writingTool", systemImage: "pencil.and.outline", category: .ai),
        .imagePlayground: ActionMetadata(displayNameKey: "action.imagePlayground", systemImage: "photo.on.rectangle.angled", category: .ai),
        .appIntent: ActionMetadata(displayNameKey: "action.appIntent", systemImage: "app.badge.checkmark", category: .appIntents),
        .appAction: ActionMetadata(displayNameKey: "action.appAction", systemImage: "app.badge", category: .appIntents),
        .findApp: ActionMetadata(displayNameKey: "action.findApp", systemImage: "magnifyingglass", category: .appIntents),
        .automation: ActionMetadata(displayNameKey: "action.automation", systemImage: "bolt.heart", category: .automation),
        .findAutomation: ActionMetadata(displayNameKey: "action.findAutomation", systemImage: "magnifyingglass.circle", category: .automation),
        .automationRun: ActionMetadata(displayNameKey: "action.automationRun", systemImage: "play.circle.fill", category: .automation),
        .trigger: ActionMetadata(displayNameKey: "action.trigger", systemImage: "bolt", category: .automation),
    ]
}
